In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import polars as pl
import gc
from ydata_profiling import ProfileReport

In [3]:
trips_df = pl.read_csv(source="data/trips_dataset.csv" , infer_schema_length = 10000)

individuals_df = pl.read_csv(source="data/individuals_dataset.csv" , infer_schema_length=10000)

In [4]:
trips_df.shape , individuals_df.shape

((80697, 27), (3337, 27))

In [5]:
individuals_with_trips_df = individuals_df.join(other = trips_df, on=["ID"], how ="inner" , suffix="_right" , coalesce=True)

In [6]:
individuals_with_trips_df

shape: (80_697, 53)
┌─────────┬────────┬──────────────────┬───────┬───┬────────┬────────┬────────┬────────────┐
│ ID      ┆ CODGEO ┆ AREA_NAME        ┆ SEX   ┆ … ┆ Mode_3 ┆ Mode_4 ┆ Mode_5 ┆ Weight_Day │
│ ---     ┆ ---    ┆ ---              ┆ ---   ┆   ┆ ---    ┆ ---    ┆ ---    ┆ ---        │
│ str     ┆ i64    ┆ str              ┆ str   ┆   ┆ str    ┆ str    ┆ str    ┆ f64        │
╞═════════╪════════╪══════════════════╪═══════╪═══╪════════╪════════╪════════╪════════════╡
│ 42_0001 ┆ 91589  ┆ Savigny-sur-Orge ┆ Woman ┆ … ┆ null   ┆ null   ┆ null   ┆ 97.171946  │
│ 42_0001 ┆ 91589  ┆ Savigny-sur-Orge ┆ Woman ┆ … ┆ null   ┆ null   ┆ null   ┆ 92.090337  │
│ 42_0001 ┆ 91589  ┆ Savigny-sur-Orge ┆ Woman ┆ … ┆ null   ┆ null   ┆ null   ┆ 92.090337  │
│ 42_0001 ┆ 91589  ┆ Savigny-sur-Orge ┆ Woman ┆ … ┆ null   ┆ null   ┆ null   ┆ 92.090337  │
│ 42_0001 ┆ 91589  ┆ Savigny-sur-Orge ┆ Woman ┆ … ┆ null   ┆ null   ┆ null   ┆ 92.090337  │
│ …       ┆ …      ┆ …                ┆ …     ┆ … ┆ …      ┆ …      ┆ …      ┆ …          │
│ 4_2386  ┆ 77359  ┆ Perthes          ┆ Woman ┆ … ┆ null   ┆ null   ┆ null   ┆ 124.509471 │
│ 4_2386  ┆ 77359  ┆ Perthes          ┆ Woman ┆ … ┆ null   ┆ null   ┆ null   ┆ 124.509471 │
│ 4_2386  ┆ 77359  ┆ Perthes          ┆ Woman ┆ … ┆ null   ┆ null   ┆ null   ┆ 124.509471 │
│ 4_2386  ┆ 77359  ┆ Perthes          ┆ Woman ┆ … ┆ null   ┆ null   ┆ null   ┆ 121.119931 │
│ 4_2386  ┆ 77359  ┆ Perthes          ┆ Woman ┆ … ┆ null   ┆ null   ┆ null   ┆ 121.119931 │
└─────────┴────────┴──────────────────┴───────┴───┴────────┴────────┴────────┴────────────┘

In [7]:
individuals_with_trips_df.describe()

shape: (9, 54)
┌────────────┬─────────┬──────────────┬───────────┬───┬─────────┬─────────┬─────────┬─────────────┐
│ statistic  ┆ ID      ┆ CODGEO       ┆ AREA_NAME ┆ … ┆ Mode_3  ┆ Mode_4  ┆ Mode_5  ┆ Weight_Day  │
│ ---        ┆ ---     ┆ ---          ┆ ---       ┆   ┆ ---     ┆ ---     ┆ ---     ┆ ---         │
│ str        ┆ str     ┆ f64          ┆ str       ┆   ┆ str     ┆ str     ┆ str     ┆ f64         │
╞════════════╪═════════╪══════════════╪═══════════╪═══╪═════════╪═════════╪═════════╪═════════════╡
│ count      ┆ 80697   ┆ 80697.0      ┆ 80697     ┆ … ┆ 2212    ┆ 235     ┆ 20      ┆ 80696.0     │
│ null_count ┆ 0       ┆ 0.0          ┆ 0         ┆ … ┆ 78485   ┆ 80462   ┆ 80677   ┆ 1.0         │
│ mean       ┆ null    ┆ 85852.295909 ┆ null      ┆ … ┆ null    ┆ null    ┆ null    ┆ 407.519873  │
│ std        ┆ null    ┆ 8259.760338  ┆ null      ┆ … ┆ null    ┆ null    ┆ null    ┆ 443.426629  │
│ min        ┆ 10_2978 ┆ 75101.0      ┆ Ablis     ┆ … ┆ BIKE    ┆ BIKE    ┆ BIKE    ┆ 0.0         │
│ 25%        ┆ null    ┆ 77215.0      ┆ null      ┆ … ┆ null    ┆ null    ┆ null    ┆ 124.509471  │
│ 50%        ┆ null    ┆ 91338.0      ┆ null      ┆ … ┆ null    ┆ null    ┆ null    ┆ 256.714372  │
│ 75%        ┆ null    ┆ 93051.0      ┆ null      ┆ … ┆ null    ┆ null    ┆ null    ┆ 462.750015  │
│ max        ┆ 7_2976  ┆ 95680.0      ┆ Yerres    ┆ … ┆ WALKING ┆ WALKING ┆ WALKING ┆ 2354.990369 │
└────────────┴─────────┴──────────────┴───────────┴───┴─────────┴─────────┴─────────┴─────────────┘

In [8]:
individuals_with_trips_df.null_count()

shape: (1, 53)
┌─────┬────────┬───────────┬─────┬───┬────────┬────────┬────────┬────────────┐
│ ID  ┆ CODGEO ┆ AREA_NAME ┆ SEX ┆ … ┆ Mode_3 ┆ Mode_4 ┆ Mode_5 ┆ Weight_Day │
│ --- ┆ ---    ┆ ---       ┆ --- ┆   ┆ ---    ┆ ---    ┆ ---    ┆ ---        │
│ u32 ┆ u32    ┆ u32       ┆ u32 ┆   ┆ u32    ┆ u32    ┆ u32    ┆ u32        │
╞═════╪════════╪═══════════╪═════╪═══╪════════╪════════╪════════╪════════════╡
│ 0   ┆ 0      ┆ 0         ┆ 0   ┆ … ┆ 78485  ┆ 80462  ┆ 80677  ┆ 1          │
└─────┴────────┴───────────┴─────┴───┴────────┴────────┴────────┴────────────┘

In [14]:
dtypes_dict = {col: individuals_with_trips_df[col].dtype for col in individuals_with_trips_df.columns}
dtypes_dict

{'ID': String,
 'CODGEO': Int64,
 'AREA_NAME': String,
 'SEX': String,
 'AGE': Int64,
 'DIPLOMA': String,
 'PRO_CAT': Int64,
 'TYPE_HOUSE': String,
 'NBPERS_HOUSE': Int64,
 'NB_10': Int64,
 'NB_11_17': Float64,
 'NB_18_24': Float64,
 'NB_25_64': Int64,
 'NB_65': Int64,
 'PMR': Boolean,
 'DRIVING_LICENCE': Boolean,
 'NB_CAR': Int64,
 'TWO_WHEELER': String,
 'BIKE': String,
 'ELECT_SCOOTER': String,
 'NAVIGO_SUB': Boolean,
 'IMAGINER_SUB': Boolean,
 'OTHER_SUB_PT': Boolean,
 'BIKE_SUB': Boolean,
 'NSM_SUB': Boolean,
 'WEIGHT_INDIV': Float64,
 'GPS_RECORD': Boolean,
 'KEY': String,
 'Day_EMG': String,
 'Date_EMG': Date,
 'Day_Type': String,
 'ID_Trip_Days': String,
 'Type_Trip_OD': String,
 'Area_O': String,
 'Area_D': String,
 'Code_INSEE_O': String,
 'Code_INSEE_D': String,
 'Zone_O': String,
 'Zone_D': String,
 'Date_O': Date,
 'Time_O': Time,
 'Date_D': Date,
 'Time_D': Time,
 'Duration': Float64,
 'Purpose_O': String,
 'Purpose_D': String,
 'Main_Mode': String,
 'Mode_1': String,
 'Mode_2': String,
 'Mode_3': String,
 'Mode_4': String,
 'Mode_5': String,
 'Weight_Day': Float64}

In [10]:
individuals_with_trips_df.filter(pl.col("GPS_RECORD") == False).height/individuals_with_trips_df.shape[0]/100

#TODO: individuals who have no gps records are about 4% of the population so I may filter or drop them

3.705218285685961e-05

In [11]:
individuals_with_trips_df = individuals_with_trips_df.filter(pl.col("GPS_RECORD") == True)

individuals_with_trips_df = individuals_with_trips_df.with_columns([
    pl.col("Date_EMG").str.to_date(strict=False),
    pl.col("Date_O").str.to_date(strict=False),
    pl.col("Date_D").str.to_date(strict=False),
    pl.col("Time_O").str.to_time(strict=False),
    pl.col("Time_D").str.to_time(strict=False)

    ]
)

In [13]:
ProfileReport(individuals_with_trips_df.to_pandas(),minimal=False , tsmode=False, title="Profiling Report" , explorative=True).to_file("report.html")

Summarize dataset:  55%|█████▌    | 32/58 [00:03<00:15,  1.69it/s, Describe variable: Mode_4]
Summarize dataset:  71%|███████   | 41/58 [00:04<00:14,  1.16it/s, Describe variable: Weight_Day]
Summarize dataset:  79%|███████▉  | 46/58 [00:04<00:05,  2.26it/s, Describe variable: Weight_Day]
Summarize dataset:  79%|███████▉  | 46/58 [00:05<00:05,  2.26it/s, Describe variable: Weight_Day]
Summarize dataset:  81%|████████  | 47/58 [00:05<00:04,  2.34it/s, Describe variable: Weight_Day]
100%|██████████| 53/53 [00:01<00:00, 32.32it/s]5<00:02,  3.48it/s, Describe variable: Weight_Day]
Summarize dataset: 100%|██████████| 127/127 [00:15<00:00,  8.12it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:07<00:00,  7.22s/it]
Render HTML: 100%|██████████| 1/1 [00:01<00:00,  1.39s/it]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 94.26it/s]

## Extensive Data Analysis